# Generated by Django 4.0.4 on 2022-10-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifest2022', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='staffAuth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
