# Generated by Django 4.0.4 on 2022-10-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifest2022', '0004_profile_staffauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gold',
            field=models.BooleanField(default=False),
        ),
    ]
