# Generated by Django 4.0.4 on 2022-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifest2022', '0006_profile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
