# Generated by Django 4.0.4 on 2022-11-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iohunt', '0002_alter_player_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Round',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='Round',
            field=models.IntegerField(null=True),
        ),
    ]
