# Generated by Django 4.0.4 on 2022-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iohunt', '0005_alter_player_endtime_alter_player_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='link',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
